services:
#    simplylink_resource_server.example:
#        class: SimplyLink\ResourceServerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]



    simplylink.oauth.resource_server:
            class: SimplyLink\ResourceServerBundle\Utils\SLoAuthTokenValidator
            arguments: ["%auth_username","%auth_password"]



    simplylink.oauth.resource_server.guard:
        class: SimplyLink\ResourceServerBundle\Security\SLTokenAuthenticator


    simplylink.oauth.resource_server.client:
        class: SimplyLink\ResourceServerBundle\Security\SLClientProvider

